// flow-typed signature: 960b7b5c539589b0fae51223ff7d2fa8
// flow-typed version: <<STUB>>/react-calculator-input_v^1.1.1/flow_v0.97.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-calculator-input'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-calculator-input' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-calculator-input/lib/Calculator' {
  declare module.exports: any;
}

declare module 'react-calculator-input/lib/CalculatorDisplay' {
  declare module.exports: any;
}

declare module 'react-calculator-input/lib/ConfirmButton' {
  declare module.exports: any;
}

declare module 'react-calculator-input/lib/Form' {
  declare module.exports: any;
}

declare module 'react-calculator-input/lib/index' {
  declare module.exports: any;
}

declare module 'react-calculator-input/lib/index' {
  declare module.exports: any;
}

declare module 'react-calculator-input/lib/KeyButton' {
  declare module.exports: any;
}

declare module 'react-calculator-input/lib/NumericInput' {
  declare module.exports: any;
}

declare module 'react-calculator-input/lib/NumericKeys' {
  declare module.exports: any;
}

declare module 'react-calculator-input/lib/NumericKeys' {
  declare module.exports: any;
}

declare module 'react-calculator-input/lib/NumericOps' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-calculator-input/lib/Calculator.js' {
  declare module.exports: $Exports<'react-calculator-input/lib/Calculator'>;
}
declare module 'react-calculator-input/lib/CalculatorDisplay.js' {
  declare module.exports: $Exports<'react-calculator-input/lib/CalculatorDisplay'>;
}
declare module 'react-calculator-input/lib/ConfirmButton.js' {
  declare module.exports: $Exports<'react-calculator-input/lib/ConfirmButton'>;
}
declare module 'react-calculator-input/lib/Form.js' {
  declare module.exports: $Exports<'react-calculator-input/lib/Form'>;
}
declare module 'react-calculator-input/lib/index.js' {
  declare module.exports: $Exports<'react-calculator-input/lib/index'>;
}
declare module 'react-calculator-input/lib/index.jsx' {
  declare module.exports: $Exports<'react-calculator-input/lib/index'>;
}
declare module 'react-calculator-input/lib/KeyButton.js' {
  declare module.exports: $Exports<'react-calculator-input/lib/KeyButton'>;
}
declare module 'react-calculator-input/lib/NumericInput.js' {
  declare module.exports: $Exports<'react-calculator-input/lib/NumericInput'>;
}
declare module 'react-calculator-input/lib/NumericKeys.js' {
  declare module.exports: $Exports<'react-calculator-input/lib/NumericKeys'>;
}
declare module 'react-calculator-input/lib/NumericKeys.jsx' {
  declare module.exports: $Exports<'react-calculator-input/lib/NumericKeys'>;
}
declare module 'react-calculator-input/lib/NumericOps.js' {
  declare module.exports: $Exports<'react-calculator-input/lib/NumericOps'>;
}
